dist: focal

language: python
python: "3.11"

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  # Run migrations so tests don’t crash
  - python manage.py migrate --noinput

script:
  - black .
  - black --check .
  - flake8 .
  - coverage run manage.py test
  - python test_ci.py

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: django-app
  env: Django-app-env
  bucket_name: elasticbeanstalk-us-east-1-188772318764
  on:
    repo: dhritykachhwaha/swe1-app
    branch: main
  skip_cleanup: true
