dist: focal 
language: python
script: echo "testing"
install: skip


language: python
python: "3.11"
services:
  - postgresql
addons:
  postgresql: "14"
env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings
    # Add more env vars via Travis UI for secrets (DEBUG, DATABASE_URL, etc.)
install:
  - pip install -r requirements.txt
script:
  - python test_ci.py
