dist: focal

language: python
python: "3.11"

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  # Run migrations so tests don’t crash
  - python manage.py migrate --noinput

script:
  - black --check .
  - flake8 --max-line-length=150 .
  - coverage run manage.py test
  - python test_ci.py

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: django-app
  env: Django-app-env
  bucket_name: elasticbeanstalk-us-west-2-992382724291
  on:
    branch: main
  skip_cleanup: true
